FROM gcc AS build
WORKDIR /app
COPY . .
RUN make

# FROM debian:buster-slim
FROM ubuntu:latest
RUN apt-get update && apt-get install -y make git libyaml-dev
WORKDIR /app
COPY --from=build /app /app/
COPY ./configurations/server.yaml /app/configurations/
ENV LD_LIBRARY_PATH=/usr/local/lib
CMD ["make", "server"]

